name: Build and Deploy to GCE with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}  # Docker Hub username in GitHub Secrets
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}  # Docker Hub access token in GitHub Secrets

      # 4. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t minturtle/careersupport:latest .

      # 5. Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push minturtle/careersupport:latest

  deploy:
    name: Deploy to GCE via SSH
    runs-on: ubuntu-latest
    needs: build

    steps:
      # 1. Checkout the repository (to get docker-compose.yml)
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.GCE_SSH_PRIVATE_KEY }}  # SSH private key stored in GitHub Secrets

      # 3. Deploy to GCE
      - name: Deploy to Google Compute Engine
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.GCE_USER }}@${{ secrets.GCE_HOST }} << 'EOF'
            cd /home/ubuntu
            sudo docker-compose pull  # Pull the latest Docker image
            sudo docker-compose up -d  # Run Docker Compose in detached mode
          EOF
